### ISSUE TITLE
Background is Asynchronous 

### ISSUE THREAD

**Issue by rclamb27** [rclamb27/First-Necromancer-Game#5]
Background is kind of bland and monotonous would like to add some more variety. Also the screen has a slight tear at parts when the game is running.

**Comment by kennykytran** [comment]
Hello, I'd like to contribute to this issue! I plan to add parallax scrolling and a second background behind the pillars that scroll at a different rate than the tiles. I also see that the tears are due to how the tiling is set up, and I'll look at that and try to fix it as well.

**Comment by rclamb27** [comment]
Sounds good!

**Comment by rclamb27** [comment]
@ktranfullerton2000 Sounds good, I assigned it to you for now!

**Comment by kennykytran** [comment]
Great! I've made my pull request. Let me know what you think!

**Comment by rclamb27** [comment]
Fixes the issue and improves the project! Thanks!
